### ISSUE TITLE
catkin: error when building with a fresh environment

### ISSUE THREAD

**Issue by bulwahn** [bmwcarit/meta-ros#113]

**Comment by AKADiNG** [comment]
Hi, I also have the same problem, and it still not work after I add python-empy-native, python-catkin-pkg-native to the DEPENDS.

Log data is below:

Log data follows:
| DEBUG: Executing shell function do_configure
| -- The C compiler identification is GNU 8.3.0
| -- The CXX compiler identification is GNU 8.3.0
| -- Check for working C compiler: /mnt/not_raid/ning.ding/osbuilder/bstos/build/tmp/work/core2-64-bst-linux/catkin/0.7.19-1-r0/recipe-sysroot-native/usr/bin/x86_64-bst-linux/x86_64-bst-linux-gcc
| -- Check for working C compiler: /mnt/not_raid/ning.ding/osbuilder/bstos/build/tmp/work/core2-64-bst-linux/catkin/0.7.19-1-r0/recipe-sysroot-native/usr/bin/x86_64-bst-linux/x86_64-bst-linux-gcc -- works
| -- Detecting C compiler ABI info
| -- Detecting C compiler ABI info - done
| -- Detecting C compile features
| -- Detecting C compile features - done
| -- Check for working CXX compiler: /mnt/not_raid/ning.ding/osbuilder/bstos/build/tmp/work/core2-64-bst-linux/catkin/0.7.19-1-r0/recipe-sysroot-native/usr/bin/x86_64-bst-linux/x86_64-bst-linux-g++
| -- Check for working CXX compiler: /mnt/not_raid/ning.ding/osbuilder/bstos/build/tmp/work/core2-64-bst-linux/catkin/0.7.19-1-r0/recipe-sysroot-native/usr/bin/x86_64-bst-linux/x86_64-bst-linux-g++ -- works
| -- Detecting CXX compiler ABI info
| -- Detecting CXX compiler ABI info - done
| -- Detecting CXX compile features
| -- Detecting CXX compile features - done
| -- Using CATKIN_DEVEL_PREFIX: /mnt/not_raid/ning.ding/osbuilder/bstos/build/tmp/work/core2-64-bst-linux/catkin/0.7.19-1-r0/devel
| -- Using CMAKE_PREFIX_PATH: /mnt/not_raid/ning.ding/osbuilder/bstos/build/tmp/work/core2-64-bst-linux/catkin/0.7.19-1-r0/recipe-sysroot${ros_prefix};/mnt/not_raid/ning.ding/osbuilder/bstos/build/tmp/work/core2-64-bst-linux/catkin/0.7.19-1-r0/recipe-sysroot/usr
| -- Found PythonInterp: /mnt/not_raid/ning.ding/osbuilder/bstos/build/tmp/work/core2-64-bst-linux/catkin/0.7.19-1-r0/recipe-sysroot-native/usr/bin/python3-native/python3 (found suitable version "3.7.2", minimum required is "3")
| -- Using PYTHON_EXECUTABLE: /mnt/not_raid/ning.ding/osbuilder/bstos/build/tmp/work/core2-64-bst-linux/catkin/0.7.19-1-r0/recipe-sysroot-native/usr/bin/python3-native/python3
| -- Using default Python package layout
| -- Could NOT find PY_em (missing: PY_EM)
| CMake Error at cmake/empy.cmake:29 (message):
|   Unable to find either executable 'empy' or Python module 'em'...  try
|   installing the package 'python-empy'
| Call Stack (most recent call first):
|   cmake/all.cmake:165 (include)
|   CMakeLists.txt:8 (include)

I find em.py in my catkin build path,
./recipe-sysroot/usr/lib/python2.7/site-packages/em.py
./recipe-sysroot-native/usr/lib/python2.7/site-packages/em.py

So， any suggestion is appreciate, thank you.

**Comment by herb-kuta-lge** [comment]
@AKADiNG < What OpenEmbedded release series are you using? If **thud** or later, you should try the corresponding `-draft` branch, eg, if using **zeus**, try the `[zeus-draft]` branch. The instructions for building are [here](https://github.com/ros/meta-ros/wiki/OpenEmbedded-Build-Instructions).

**Comment by AKADiNG** [comment]
@herb-kuta-lge   Thank for your attention.  I worked on warrior branch and use the warrior-draft branch of meta-ros. I'd like to add both ros1-melodic and ros2-dashing into my image and then  came the problem.

I find that  "ROS_PYTHON_VERSION = "**2**"  "  in /**meta-ros1-melodic**/conf/ros-distro/include/melodic/generated/superflore-ros-distro.inc
and  "ROS_PYTHON_VERSION = "**3**"  "  in /**meta-ros2-dashing**/conf/ros-distro/include/dashing/generated/superflore-ros-distro.inc  .

After modify the ROS_PYTHON_VERSION to "2" in  meta-ros2-dashing, catkin builds successfully, but there will be some other problem when build other components.

So, what is the real way to add both ros1 and ros2 into my image.

**Comment by herb-kuta-lge** [comment]
@AKADiNG < Sorry, but `meta-ros` does not currently support adding ROS 1 packages to ROS 2 images. We weren't certain that anyone actually would use it, so we removed it from our roadmap (see the 8th item under https://github.com/ros/meta-ros/wiki/Superflore-OE-Recipe-Generation-Scheme#revision-46). We can certainly add it back. How important is this to you? How long can you afford to wait for it?

**Comment by shr-project** [comment]
@AKADiNG what other modifications you did to meta-ros warrior-draft? From this line:
```
| -- Using CMAKE_PREFIX_PATH: /mnt/not_raid/ning.ding/osbuilder/bstos/build/tmp/work/core2-64-bst-linux/catkin/0.7.19-1-r0/recipe-sysroot${ros_prefix};/mnt/not_raid/ning.ding/osbuilder/bstos/build/tmp/work/core2-64-bst-linux/catkin/0.7.19-1-r0/recipe-sysroot/usr
```
it looks like ros_opt_prefix (which sets ros_prefix) wasn't inherited in your build, but it should be from:
```
meta-ros1/classes/ros1_distro.bbclass:inherit ros_opt_prefix
```
Normally this line looks like this:
```
-- Using CMAKE_PREFIX_PATH: ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/catkin/0.7.23-1-r0/recipe-sysroot/opt/ros/melodic;ros1-melodic-thud/tmp-glibc/work/core2-64-oe-linux/catkin/0.7.23-1-r0/recipe-sysroot/usr
```
and that's where it will search for dependencies. I don't see how ROS_PYTHON_VERSION would influence this part.
