### ISSUE TITLE
Cortex A5 - Poky 1.7- libroscpp.so issue

### ISSUE THREAD

**Issue by bmoraine** [bmwcarit/meta-ros#305]
Hi, 

I tried to build ROS for Atmel SAMA5D31-EK (Cortex A5) with Poky 1.7.

bitbake core-image-ros-roscore is succesful.

When I try to run roscore after exporting all environment variables :

root@sama5d3xek:/opt/ros/hydro# printenv
USER=root
LD_LIBRARY_PATH=/opt/ros/hybro/lib
OLDPWD=/opt/ros/hydro/lib
HOME=/home/root
HUSHLOGIN=FALSE
PS1=\u@\h:\w\$
LOGNAME=root
TERM=linux
PATH=/opt/ros/hydro/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin
ROS_ROOT=/opt/ros/hydro
SHELL=/bin/sh
HZ=100
ROS_MASTER_URI=http://sama5d3xek:11311
PWD=/opt/ros/hydro
PYTHONPATH=/opt/ros/hydro/lib/python2.7/site-packages
TZ=UTC
CMAKE_PREFIX_PATH=/opt/ros/hydro
EDITOR=/bin/vi

I face following link error with libroscpp.so : 

root@sama5d3xek:/opt/ros/hydro/lib# roscore
... logging to /home/root/.ros/log/275a100a-7400-11e4-a5c4-766d6caec655/roslaunch-sama5d3xek-1282.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://sama5d3xek:51091/
ros_comm version 1.10.11
# SUMMARY

PARAMETERS
- /rosdistro
- /rosversion

NODES

auto-starting new master
process[master]: started with pid [1299]
ROS_MASTER_URI=http://sama5d3xek:11311/

setting /run_id to 275a100a-7400-11e4-a5c4-766d6caec655
/opt/ros/hydro/lib/rosout/rosout: error while loading shared libraries: libroscpp.so: cannot open shared object file: No such file or directory
process[rosout-1]: started with pid [1312]
started core service [/rosout]
[rosout-1] process has died [pid 1312, exit code 127, cmd /opt/ros/hydro/lib/rosout/rosout __name:=rosout __log:=/home/root/.ros/log/275a100a-7400-11e4-a5c4-766d6caec655/rosout-1.log].
log file: /home/root/.ros/log/275a100a-7400-11e4-a5c4-766d6caec655/rosout-1_.log
respawning...
[rosout-1] restarting process
/opt/ros/hydro/lib/rosout/rosout: error while loading shared libraries: libroscpp.so: cannot open shared object file: No such file or directory
process[rosout-1]: started with pid [1315]
[rosout-1] process has died [pid 1315, exit code 127, cmd /opt/ros/hydro/lib/rosout/rosout __name:=rosout __log:=/home/root/.ros/log/275a100a-7400-11e4-a5c4-766d6caec655/rosout-1.log].
log file: /home/root/.ros/log/275a100a-7400-11e4-a5c4-766d6caec655/rosout-1_.log
respawning...

And It loops infinitely...

Is my configuration wrong?

Regards

Baptiste Moraine

**Comment by GuzMp** [comment]
What do you put in DISTRO in conf/local.conf ?
I already built a bitbake core-image-sato with DISTRO?="poky" in conf/local.conf for NVIDIA jetson-tx1.
Now I want to add ROS.

**Comment by bulwahn** [comment]
Dear @GuzMp, please check http://wiki.ros.org/hydro/Installation/OpenEmbedded. For an extended answer to your question, please raise the question again either at answers.ros.org and add a link to that question here, or ask it on the meta-ros mailing list. Both are better places for larger audiences and it increases the sustainability of the supporting effort for the people providing answers.
