### ISSUE TITLE
nothing provides ros2 >= 0.9.0.5 needed by rcpputils-1.1.0-1-r0.aarch64

### ISSUE THREAD

**Issue by yiyibst** [bmwcarit/meta-ros#953]
I am working on warrior branch, I develop a embedded system and provide the customers a toolchain for this target. The toolchain is generated by the populate_sdk task， The customers' apps depend on ros2-foxy, so I need to add the cyclonedds into toolchain.
When I added some rcpputils, the compiler reported an error.
Collected errors:
 * Solver encountered 1 problem(s):
 * Problem 1/1:
 *   - nothing provides ros2 >= 0.9.0.5 needed by rcpputils-1.1.0-1-r0.aarch64
 * 
 * Solution 1:
 *   - do not ask to install a package providing rcpputils
How do I solve this problem?

**Comment by shr-project** [comment]
warrior is EOL for over a year already, see https://wiki.yoctoproject.org/wiki/Releases

meta-ros warrior branch is also unsupported, you'll need to debug this on your own unless someone else from community responds to this ticket

**Comment by yiyibst** [comment]
Thanks, but I still hope someone can help me

**Comment by robwoolley** [comment]
Closing as Warrior is no longer supported.
