### ISSUE TITLE
I'm confused on the .mcf File

### ISSUE THREAD

**Issue by kmelgar5** [bmwcarit/meta-ros#955]
I am very confused on where or how the meta-ros1-melodic-hardknott.mcf file is created. This step is confusing me when the file does not exist. Anyone have a reference to a step by step guide. 
cfg=$distro-$ros_distro-$oe_release_series.mcf
cp build/files/$cfg conf/.

**Comment by shr-project** [comment]
The $distro is just ros1 and ros1-melodic-hardknott.mcf does exist in the build branch, see https://github.com/ros/meta-ros/blob/build/files/ros1-melodic-hardknott.mcf

**Comment by kmelgar5** [comment]
Thanks for the response. In order to not open another thread, pillow seems to fail to install. Any chance you have the answer to that?

**Comment by shr-project** [comment]
You would need to provide more details, because it doesn't fail to install for me.

**Comment by kmelgar5** [comment]
While bit baking ros-image-core the following errors occur:
`ERROR: python-pillow-5.1.0-r0 do_fetch: Fetcher failure: Unable to find revision fda33d5c09142c4bb0e99964919d01c2cc5f5995 in branch master even from upstream
ERROR: python-pillow-5.1.0-r0 do_fetch: Fetcher failure for URL: 'git://github.com/python-pillow/Pillow;protocol=https'. Unable to fetch URL from any source.
ERROR: Logfile of failure stored in: /home/usr/QQ/build-xwayland-edm-g-imx8mp/tmp/work/cortexa53-crypto-poky-linux/python-pillow/5.1.0-r0/temp/log.do_fetch.918306
ERROR: Task (/home/usr/QQ/meta-ros/meta-ros-python2/recipes-devtools/python/python-pillow_5.1.0.bb:do_fetch) failed with exit code '1'
`
I've tried replacing SRCREV = "main" and it fetched the latest hash for the main method and the same error occured

**Comment by shr-project** [comment]
SRCREV is something else, see https://github.com/ros/meta-ros/pull/958
